name: build
on: push

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    env:
      IMAGE_NAME: ghcr.io/epic-r-us/garden

    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download phpBB
        run: |
          curl -OL \
            https://download.phpbb.com/pub/release/3.3/3.3.10/phpBB-3.3.10.zip

      - name: Unzip phpBB
        run: unzip phpBB-*

      - name: Docker Build
        run: docker build -t $IMAGE_NAME:latest .

      - name: Docker Push
        run: docker push --all-tags $IMAGE_NAME
